### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by akhtyamovpavel** [masha239/Quotes#1]
Привет!

Посмотрел проект - в целом, неплохо, но есть некоторые моменты, на которые я хотел обратить внимание:

- [x] код парсинга стоит вынести в Python-файлы, чтобы можно было запускать их независимо от того, есть ли ноутбук или нет
- [x] https://github.com/masha239/Quotes/blob/main/main.py#L11-L22 - для этой части лучше использовать обертку в виде `if __name__ == '__main__'` - тогда будет видно, что это и есть точка входа
- [x] https://github.com/masha239/Quotes/blob/main/inverted_index.py#L11-L14 - здесь происходит дублирование кода. Можем ли мы избавиться от него?
- [x] https://github.com/masha239/Quotes/blob/main/inverted_index.py#L41-L42 - почему здесь -1? С внешнего взгляда это непонятно, лучше добавить несколько переменных, чтобы картина разъяснилась
- [x] Каждую ячейку ноутбука можно обернуть в отдельную функцию, чтобы ее можно было потом вызывать, если мы захотим улучшать наш парсер

Буду ждать обновленную версию! Стараемся максимально выносить код из ноутбуков

**Comment by masha239** [comment]
> 



> * https://github.com/masha239/Quotes/blob/main/inverted_index.py#L11-L14 - здесь происходит дублирование кода. Можем ли мы избавиться от него?

Это логическая часть алгоритма. Сперва мы идем с шагом step, затем с шагом 1, когда с шагом step больше не можем. Можно, конечно, вынести "хождение" в доп. функцию, но в данном случае это сделает код более громоздким и менее читаемым.

Остальное исправила.

**Comment by masha239** [comment]
done
